"""
Django settings for viajero_plus project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent





# Directorio base del proyecto
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))








# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.1.214',  # <-- tu IP
    'build.dev.travel-sys.loc',
]




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'apps.usuarios',
    'apps.backoffice',
    'apps.renta_hoteles',
    'apps.renta_autos',
    'apps.vuelos',
    'apps.gestion_economica',
    'apps.booking',
    'apps.finanzas',

    'viajero_plus',  # esta sí puede quedarse como está si sigue al mismo nivel que manage.py
    'django_celery_beat',
    'dal',
    'dal_select2',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'viajero_plus.middleware.AutoLogoutMiddleware',  
    'django.middleware.locale.LocaleMiddleware',

    
]

ROOT_URLCONF = 'viajero_plus.urls'

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
            ],
        },
    },
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

WSGI_APPLICATION = 'viajero_plus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# BD LOCAL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',      # Motor de base de datos SQLite
        'NAME': BASE_DIR / 'db.sqlite3',             # Ruta del archivo de la base de datos dentro del proyecto
    }
}

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'db_build',
#        'USER': 'newneo20',
#        'PASSWORD': '0123456789',
#        'HOST': 'store.prod.travel-sys.loc',
#        'PORT': '5432',
#        'OPTIONS': {
#            'sslmode': 'require',
#        },
#    },
#    'readonly': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'NAME': 'db_build',
#        'USER': 'newneo20',
#        'PASSWORD': '0123456789',
#        'HOST': 'store.prod.travel-sys.loc',
#        'PORT': '5433',
#        'OPTIONS': {
#            'sslmode': 'require',
#        },
#    }
#}

# 🚦 Aquí se especifica el enrutador de bases de datos personalizado
DATABASE_ROUTERS = ['apps.common.routers.ReadOnlyRouter']




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.CustomUser'

LOGIN_URL = '/usuarios/login/'
LOGIN_REDIRECT_URL = '/usuarios/dashboard/'

# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Usa Redis como broker
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Tiempo de expiración de sesión (en segundos)
# 1 minuto         →  60
# 10 minutos       →  600
# 15 minutos       →  900
# 30 minutos       →  1800
# 1 hora           →  3600
# 2 horas          →  7200
# 3 horas          →  10800
# 1 día completo   →  86400
SESSION_COOKIE_AGE = 1800  # (actual: 30 minutos aprox.)

SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Opcional: Cierra la sesión al cerrar el navegador
SESSION_SAVE_EVERY_REQUEST = True  # Actualiza la sesión en cada solicitud del usuario
